//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cauhinh
    {
        public Cauhinh()
        {
            this.Serials = new HashSet<Serial>();
        }
    
        public int id { get; set; }
        public string Chip { get; set; }
        public string RAM { get; set; }
        public string HDD { get; set; }
        public string SSD { get; set; }
        public string Main { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Serial> Serials { get; set; }
    }
}
