//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Don_vi
    {
        public Don_vi()
        {
            this.Phong_ban = new HashSet<Phong_ban>();
        }
    
        public int id { get; set; }
        public string namepj { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Phong_ban> Phong_ban { get; set; }
    }
}
