//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goithau
    {
        public Goithau()
        {
            this.Thietbis = new HashSet<Thietbi>();
        }
    
        public int id { get; set; }
        public Nullable<int> idprj { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual Pro Pro { get; set; }
        public virtual ICollection<Thietbi> Thietbis { get; set; }
    }
}
