//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serial
    {
        public int id { get; set; }
        public Nullable<int> id_Tb { get; set; }
        public Nullable<int> id_Ch { get; set; }
        public string SerialNumber { get; set; }
        public string description { get; set; }
        public string Mathietbi { get; set; }
    
        public virtual Cauhinh Cauhinh { get; set; }
        public virtual Thietbi Thietbi { get; set; }
    }
}
