//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thietbi
    {
        public Thietbi()
        {
            this.Serials = new HashSet<Serial>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string Mathietbi { get; set; }
        public Nullable<int> id_goithau { get; set; }
    
        public virtual Goithau Goithau { get; set; }
        public virtual ICollection<Serial> Serials { get; set; }
    }
}
